language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: sebZjrW2Vj3MaHTxe37ZrKZ7mItKDYWweZ+34NuuGLGgl0ksrRc19Ie4mJL12xZenE94nnbHViYF+VkYO/ilo2PeQkY8JkmXUywsrMyUZgvhTipgi/eOiicTVPAXk7XBqW9qvzuy0NLIcIY0OiFQeLDIuKiw3pZDPFruwTFVqpQL8SOpH9yzU+0dcBmKCukyjnuSoH45XfqqFrIfLx4YXd0JS8LFt4Tb8VnK99A2k9H9QTpIH9WaTIaowANfBAcxaJfGx0CTMvGNNQYzTRjvnLo8TtJeyClkE7sNTtrkdmyGet0tWF3yPw2wm1MIN9md/1qaGDNFAJMKPO+Kp2EQFERbhN1hMRvdK/rqBLSX5DDutgY2xiludGX/gy+dWCWKscpAbWk1I4LKe1mw1K6M0lFKowRCQZhnQnrEfPAWW1RqkEHY1JJeHdXt8R6eN0RMqW4j0vBIDtZJB+486PmmQH+5kpv+gpqMVgV8LntE5ynoC2pX380/ni6lLuLKsv1nKanEvY5H3Z1Tcl35mbLcQw4XQpR4uOCP7xMlkxdjTU8TgwJh/T5KbYTaYaHMMUR90xJNWzz6U0a5D8qorlLY59LlqWeJ147L7heJ51vt6XivvajrOJHOVGRTao4SFYiDkwcnSUjLDIvglEDwCVlP36i5YOIych0Xups5WyBOzXY=
  app: node-shopping-list-integration-tests
  on:
    repo: surbhiguptasai/node-shopping-list-integration-tests
