language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: RKJAADqhy0mkw/XzHMOR9nkpD57AUB/EgNY2jnTUFX8yBaUa55bLg+wKyYJoQph10BYuzuyZTL02VaYww6PsZX7HShNWw+J/U/xZ4IFbyTdaYtcBDmppqsQPakq1N4p1jJaIp/SsX9mugqYPehslyHQlB2CYQnIiLUOgdD6Vk1Q93Ng0gycf7QxEUwyCauT/m8C499EjtdggGmaDObNeUVcU+Lp/MRylk2ZCZGEDW5zlrO3ecK8sBdOLD6BtYfvCf+QODfSqQbeqWZ5AFHkuX8tqJELum0zc3Exv7TWwbGqfBq4UFvheCqAO1NT//2HCi6DcoR3vZ4oLvU5jyjygnrJd5xVtJg7AJDotVsaIGjbhjz9E/M1USlB5meC+QlX8/HGu/h2dymt2QSWeex0gmJ67t1XJkzUJRxMYOEjXKTCnoI8FA39GxsZewv/1+rmcdnJZigA4/PYxY2TALYDJS52WdZ+Splr8hU5nygNyP3gQWOawQRhKmlzMwQwO/XRTgctrfTCBX3Wmd/18+VWrCJz+o/2ct6jtyf/CcrLByJIvJgAoYuiknvR0YvvWMAUj2ARRRFCI3UbIDZpxsGELRmFbAVC2TwK4fIp5rp4lCmyrX2WBCeceo9jE3JHAAYNnvbqcHKA+UPv9gIXvjKi0VFd1bK663dyHFa4c0CPwkMk=
  app: node-shopping-list-integration-tests
  on:
    repo: surbhiguptasai/node-shopping-list-integration-tests
